---
title: "Prototype main.Rmd - model-based algorithm"
author: "Daniel J. Parker"
output: html_notebook
---

This code is based on the Group 8 Project 4 Fall 2017 repository at https://github.com/TZstatsADS/Fall2017-project4-grp8. This notebook is intended to implement only the Expectation-Maximization (EM) statistical machine learning algorithm.

# Specify Directories
```{r}
# Web dataset: training and testing directories
web_train <- "../data/MS_sample/data_train"
web_test <- "../data/MS_sample/data_test"

# Movie dataset: training and test directories
movie_train <- "../data/eachmovie_sample/data_train"
movie_test <- "../data/eachmovie_sample/data_test"
```

# Read Data
```{r}
# Web dataset: training and testing data read-in
web_train <- read.csv(paste0(web_train, ".csv"))
web_test <- read.csv(paste0(web_test, ".csv"))

# Movie dataset: training and test data read-in
movie_train <- read.csv(paste0(movie_train, ".csv"))
movie_test <- read.csv(paste0(movie_test, ".csv"))
```

# Pre-Process Data
```{r}
source("../lib/transform.R")
# Function `transform_MS` creates the user-item matrix for the MS data.
# Function `transform_movie` creates the user-item matrix for the movie data.
web_train <- transform_MS(web_train)
web_test <- transform_MS(web_test)
movie_train <- transform_movie(movie_train)
movie_test <- transform_movie(movie_test)

# Save the pre-processed dataframes for future reference.
save(web_train, file = "../output/web_train_UI.RData")
save(web_test, file = "../output/web_test_UI.RData")
save(movie_train, file = "../output/movie_train_UI.RData")
save(movie_test, file = "../output/movie_test_UI.RData")
```

# Model-Based Algorithm
```{r}
source("../lib/expectation_maximization.R")
```

# Next Step?
```{r}
# What does this code do?
data_train <- read.csv("../data/eachmovie_sample/data_train.csv")
data_train<-as.data.frame(data_train[,-1])
data_train[is.na(data_train)] <- 0
row.names(data_train)<-data_train[,1]
data_train<-as.data.frame(data_train[,-1])
movie.index<-substring(names(data_train), 7)
colnames(data_train)<-1:ncol(data_train)

# Construct a binary matrix for users & moives 
data<-rep(NA,nrow(data_train))
for (i in 1:6){
  dat<-data_train
  dat[dat==i]<-1
  dat[dat!=i]<-0
  data<-cbind(data,dat)
}
data<-data[,-1]
```
